### ISSUE TITLE
Round the expected results

### ISSUE THREAD

**Issue by fredck** [pjasiun/fuma#52]
Right now we have results like `(10 : 6.72)`... the decimal part is totally pointless and it's actually confusing.

We learned how to round it in our heads, but it would be nice if Fuma would simply show it rounded straight.

**Comment by jodator** [comment]
@fredck that is not entirely true. It is not that confusing for all.
`10 : 6.72` is different then `10 : 6:13` or so...

Any way proper rounding (`6.73 ~ 7` and `6.13 ~ 6`) might be better but those numbers after decimal point give you some clue about how close you have to be to given score.

Anyway if you gather upvotes it might be implemented fast.

**Comment by pjasiun** [comment]
There is no reason to round that value. It is the proportion of probability of winning.

Also, it does matter if the "expected results" is `10 : 6.51` or `10 : 7:49`, because if you score `10 : 7` you gain or loose points in each situation. It does especially matter in the edge cases: there is a huge difference between `10 : 1.51` and `10 : 2.49`. And, what is most important: `10 : 9.51` give you information who is better (according to the rank).

**Comment by jodator** [comment]
@pjasiun It might be worth to give it a try... Dunno rounded values might be less stressful.

**Comment by fredck** [comment]
Hahahaha... developers thinking about UX :D

**Comment by pjasiun** [comment]
You know: it's a command line app... for Slack... with fancy charts. It's clearly created for engineers, not for people ;)

**Comment by fredck** [comment]
In general, that's the talks I see out there:

```
// For a (10 : 7.82) match:

Joe: What's the expectation?
Pablo: I think 10x7 ;)
```

**Comment by fredck** [comment]
It's fine, ofc ;)

**Comment by fredck** [comment]
Er... sorry, updated the wrong example :)
